### PR TITLE
https://github.com/willthames/ansible-inventory-grapher/issues/37

### PR DESCRIPTION
**Pull request by eking-go**
Hello.

I would be grateful if you add to the main branch

Kind regards,
Nikolay

### CODE REVIEW

**Comment by billux** [comment]
Hi,

It would be nice that eking-go's contribution be merged. I'm using his branch to generate a graph of our inventory with value of some variables and I didn't notice any issue so far.

Thanks!

**Comment by gilcot** [comment]
...still pending after more than a year. Is there some hidden issue with the patch submitted?

**Comment by willthames** [comment]
No, I just don't notice every notification and the traffic to this repo is very light, so I don't actively monitor it. 

The only thing I don't like about it (and this is not a hidden issue, just the first time I've looked) is the parameter name - should be something like `--showvalues` to match `--showvars`

**Comment by eking-go** [comment]
Hello. You can rename this option as you like. It not matter, I think.

**Comment by willthames** [comment]
Merged, thanks @eking-go

**Pull request merged**
