### PR TITLE
Encourage sorting if practical, add -a ATTRIBUTES option... 

### PR DESCRIPTION
**Pull request by MTN-RowinAndruscavage**
to inject custom declarations into template, documentation updates.
Address some flake8 issues.

### CODE REVIEW

**Comment by willthames** [comment]
Is this the squashed replacement for #20?

**Comment by willthames** [comment]
Just needs commit message rewrite to meet generally accepted commit standards
http://chris.beams.io/posts/git-commit/#seven-rules

You don't need to create a new PR either - there are still some comments on #20 that apply here - repushing the squash results to the same branch would have updated #20 rather than creating a new one.

**Comment by willthames** [comment]
Ah, just seen your note on the hyperlink on #20.

**Comment by MTN-RowinAndruscavage** [comment]
Cool, thanks, I hadn't seen the seven-rules before.  I like them!   Commit message updated here.  Not brave enough to try force pushing a big squash to a remote branch yet ;-)

**Comment by willthames** [comment]
As long as it's your remote branch, it's not too bad (most things are revertible with the right force push, even if you have to look at `git reflog` a bit to work out where you need to be. 

Thanks for being so responsive to my requests for updates.

**Comment by MTN-RowinAndruscavage** [comment]
Hey, thanks for this awesome utility!  It's very useful for tracking which groups and supergroups our nodes are part of, and has also helped us identify orphan nodes that weren't quite in the groups we expected!

**Comment by willthames** [comment]
Yeah, also for when you think one group is a child of another group but then find out it's accidentally a sibling - I'm really pleased that it's a relatively simple application (mainly piggybacking off ansible routines and passing off the result to graphviz) with huge benefits.

**Pull request merged**
